version: "3.8"

services:
  app:
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017