version: "3.8"

services:
  app:
    build: 
      context: ./src/back-app
      dockerfile: Dockerfile
    volumes:
      - ./src/back-app/migrations:/usr/app/migrations
    ports:
      - 3000:3000
    
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017