version: "3.8"

services:
  app:
    build: 
      context: ./src/back-app
      dockerfile: Dockerfile
    volumes:
      - "./src/back-app/code:/usr/app/code"
      - "./src/back-app/index.js:/usr/app/index.js"
    entrypoint: ["./bin/wait-for-service.sh", "db:27017"]
    ports:
      - 3000:3000
  
  front:
    build:
      context: ./src/front-app
      dockerfile: Dockerfile
    volumes:
      - ./src/front-app/src:/usr/app/src
    entrypoint: ["./bin/wait-for-service.sh", "app:3000"]
    ports:
      - 3001:3000
    
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017